#!/bin/bash

if [ ! -d ./venv/ ]
then
  echo "[!] Virtual environment at ./venv/ not found - try running the install script in ./setup"
  exit 1
fi

echo "[*] Activating python virtual environment..."
source ./venv/bin/activate

# echo "[*] Checking python dependencies..."
# pip install -U -r ./setup/requirements.txt

echo "[*] Launching Empire!"
python empire.py $@
